DROP TABLE EMP;
DROP TABLE DEPT;

CREATE TABLE DEPT (
 DEPTNO              integer NOT NULL,
 DNAME               varchar(14),
 LOC                 varchar(13),
 PRIMARY KEY (DEPTNO)
 );

INSERT INTO DEPT(DEPTNO, DNAME, LOC) VALUES (10,'ACCOUNTING','NEW YORK');
INSERT INTO DEPT(DEPTNO, DNAME, LOC) VALUES (20,'RESEARCH','DALLAS');
INSERT INTO DEPT(DEPTNO, DNAME, LOC) VALUES (30,'SALES','CHICAGO');
INSERT INTO DEPT(DEPTNO, DNAME, LOC) VALUES (40,'OPERATIONS','BOSTON');

CREATE TABLE EMP (
 EMPNO               integer NOT NULL,
 ENAME               varchar(10),
 JOB                 varchar(9),
 MGR                 integer REFERENCES EMP (EMPNO),
 HIREDATE            DATE,
 SAL                 DECIMAL(13),
 COMM                DECIMAL(5),
 DEPTNO              integer NOT NULL,
FOREIGN KEY (DEPTNO) REFERENCES DEPT (DEPTNO),
PRIMARY KEY (EMPNO)
);

INSERT INTO EMP VALUES (7839,'KING','PRESIDENT',NULL,'81-11-17',5000,NULL,10);
INSERT INTO EMP VALUES (7698,'BLAKE','MANAGER',7839,'81-05-1',2850,NULL,30);
INSERT INTO EMP VALUES (7782,'CLARK','MANAGER',7839,'81-06-9',2450,NULL,10);
INSERT INTO EMP VALUES (7566,'JONES','MANAGER',7839,'81-04-2',2975,NULL,20);
INSERT INTO EMP VALUES (7654,'MARTIN','SALESMAN',7698,'81-09-28',1250,1400,30);
INSERT INTO EMP VALUES (7499,'ALLEN','SALESMAN',7698,'81-02-20',1600,300,30);
INSERT INTO EMP VALUES (7844,'TURNER','SALESMAN',7698,'81-09-8',1500,0,30);
INSERT INTO EMP VALUES (7900,'JAMES','CLERK',7698,'81-12-3',950,NULL,30);
INSERT INTO EMP VALUES (7521,'WARD','SALESMAN',7698,'81-02-22',1250,500,30);
INSERT INTO EMP VALUES (7902,'FORD','ANALYST',7566,'81-12-3',3000,NULL,20);
INSERT INTO EMP VALUES (7369,'SMITH','CLERK',7902,'80-12-17',800,NULL,20);
INSERT INTO EMP VALUES (7788,'SCOTT','ANALYST',7566,'82-12-09',3000,NULL,20);
INSERT INTO EMP VALUES (7876,'ADAMS','CLERK',7788,'83-01-12',1100,NULL,20);
INSERT INTO EMP VALUES (7934,'MILLER','CLERK',7782,'82-01-23',1300,NULL,10);

SELECT * FROM EMP ORDER BY ENAME ASC;
SELECT SAL FROM EMP;
SELECT ENAME, SAL FROM EMP WHERE DEPTNO=10;
SELECT SAL FROM EMP WHERE SAL BETWEEN 1000 AND 5000;
SELECT * FROM EMP WHERE DEPTNO=10 OR DEPTNO=20;
SELECT * FROM EMP WHERE COMM is NULL;
SELECT * FROM EMP WHERE JOB = 'MANAGER';
SELECT ENAME, SAL,(SAL*12+IFNULL(COMM, 0)) AS CTC FROM EMP; 
SELECT ENAME, HIREDATE,DATEDIFF(CURRENT_DATE,HIREDATE)/365 AS TENURE FROM EMP;

SELECT * FROM EMP WHERE ENAME='SCOTT';
SELECT * FROM EMP WHERE SAL = (SELECT SAL FROM EMP WHERE ENAME='SCOTT');
SELECT * FROM EMP WHERE JOB = (SELECT JOB FROM EMP WHERE ENAME='SMITH');

SELECT EMP.ENAME,DEPT.DNAME
FROM EMP
INNER JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO;

SELECT CURRENT_DATE as date from emp;

SELECT DEPT.DEPTNO,DEPT.DNAME,EMP.ENAME
FROM DEPT
LEFT JOIN EMP ON DEPT.DEPTNO = EMP.DEPTNO
order by ENAME

SELECT DEPT.DEPTNO,DEPT.DNAME
FROM DEPT
LEFT JOIN EMP ON DEPT.DEPTNO = EMP.DEPTNO
WHERE EMP.DEPTNO IS NULL;


SELECT x.ENAME as Emp, y.ENAME as Boss
FROM EMP x
INNER JOIN EMP y ON x.MGR = y.EMPNO
ORDER BY x.ENAME

SELECT x.ENAME as Emp, y.ENAME as Boss
FROM EMP x
LEFT JOIN EMP y ON x.MGR = y.EMPNO;

SELECT x.ENAME as Emp, y.ENAME as Boss
FROM EMP x
LEFT JOIN EMP y ON x.MGR = y.EMPNO
WHERE y.ENAME IS NULL;

SELECT * FROM EMP WHERE MGR is null;

SELECT x.ENAME as Emp,DEPT.DNAME as DeptName, y.ENAME as Boss
FROM EMP x
INNER JOIN EMP y ON x.MGR = y.EMPNO
INNER JOIN DEPT ON x.DEPTNO = DEPT.DEPTNO;

SELECT x.ENAME as Emp,DEPT.DNAME as DeptName, y.ENAME as Boss
FROM EMP x	
LEFT JOIN EMP y ON x.MGR = y.EMPNO
INNER JOIN DEPT ON x.DEPTNO = DEPT.DEPTNO;

SELECT COUNT(*) as TotalEmployees
FROM EMP;

SELECT SUM(SAL) as SumOfSalary
FROM EMP;

SELECT AVG(SAL) as AvgOfSalary
FROM EMP;

SELECT * 
FROM EMP 
ORDER BY SAL DESC 
LIMIT 3;

SELECT COUNT(*) as TotalEmp, DEPTNO
FROM EMP
GROUP BY DEPTNO;

SELECT COUNT(*) as TotalEmp, JOB
FROM EMP
GROUP BY JOB;

SELECT COUNT(*) as TotalEmp,DEPTNO,JOB
FROM EMP
GROUP BY DEPTNO,JOB;

SELECT COUNT(*) as TotalEmp, JOB
FROM EMP
GROUP BY JOB
HAVING count(*)>2
ORDER BY JOB DESC;

SELECT COUNT(*) as TotalEmp, JOB
FROM EMP
GROUP BY JOB
HAVING count(*)>2
ORDER BY count DESC;

SELECT DNAME AS 'Department Name', 
COUNT(*) AS 'No of Employees' 
FROM DEPT 
INNER JOIN EMP 
ON EMP.DEPTNO = DEPT.DEPTNO
GROUP BY DEPT.DEPTNO, DNAME
ORDER BY DNAME DESC 

SELECT * FROM DEPT;
SELECT * FROM EMP;